"""Render and persist a user-customised ``.sqlfluff`` config file.

Settings live in ``settings.json`` as friendly key/value pairs (e.g.
``sqlfluff_keywords_case = "upper"``). On startup and after every settings
change we materialise them into a real INI config that ``SQLFormatter`` feeds
to ``FluffConfig.from_path``.

Section/key naming follows SQLFluff v3+ conventions. Note the British
spelling (``capitalisation``) and that *keywords* and *literals* use
``capitalisation_policy`` while *functions*, *identifiers*, and *types* use
``extended_capitalisation_policy`` — this is a SQLFluff API quirk, not ours.
"""
from __future__ import annotations

import os
from typing import Any, Mapping

from flatsql.config import USER_SQLFLUFF_PATH, USER_DATA_DIR
from flatsql.core.logger import get_logger

logger = get_logger(__name__)


def render_sqlfluff_config(settings: Mapping[str, Any]) -> str:
    """Build a `.sqlfluff` INI string from a settings mapping."""
    keywords_case = settings.get('sqlfluff_keywords_case', 'upper')
    functions_case = settings.get('sqlfluff_functions_case', 'upper')
    identifiers_case = settings.get('sqlfluff_identifiers_case', 'lower')
    literals_case = settings.get('sqlfluff_literals_case', 'upper')
    types_case = settings.get('sqlfluff_types_case', 'upper')

    indent_unit = settings.get('sqlfluff_indent_unit', 'space')
    tab_space_size = int(settings.get('sqlfluff_tab_space_size', 4))
    max_line_length = int(settings.get('sqlfluff_max_line_length', 80))
    comma_position = settings.get('sqlfluff_comma_position', 'trailing')
    require_semicolon = bool(settings.get('sqlfluff_require_semicolon', False))
    quote_identifiers = bool(settings.get('sqlfluff_quote_identifiers', True))

    # Note: do not write a `rules = ...` whitelist here. The high-level
    # ``sqlfluff.fix`` API silently drops patches when a whitelist is present,
    # so we rely on SQLFluff's defaults (all rules enabled) and shape behavior
    # only via per-rule sections below.
    lines: list[str] = [
        "# Generated by FlatSQL Studio. Edit via Settings → SQL Formatting.",
        "# Hand edits are overwritten when the user changes settings in the app.",
        "",
        "[sqlfluff]",
        "dialect = duckdb",
        f"max_line_length = {max_line_length}",
        "",
        "[sqlfluff:indentation]",
        f"indent_unit = {indent_unit}",
        f"tab_space_size = {tab_space_size}",
        "",
        "[sqlfluff:rules:capitalisation.keywords]",
        f"capitalisation_policy = {keywords_case}",
        "",
        "[sqlfluff:rules:capitalisation.functions]",
        f"extended_capitalisation_policy = {functions_case}",
        "",
        "[sqlfluff:rules:capitalisation.identifiers]",
        f"extended_capitalisation_policy = {identifiers_case}",
        "",
        "[sqlfluff:rules:capitalisation.literals]",
        f"capitalisation_policy = {literals_case}",
        "",
        "[sqlfluff:rules:capitalisation.types]",
        f"extended_capitalisation_policy = {types_case}",
        "",
        "[sqlfluff:layout:type:comma]",
        f"line_position = {comma_position}",
        "",
        "[sqlfluff:rules:convention.terminator]",
        f"require_final_semicolon = {require_semicolon}",
        "",
        # references.quoting (RF06) reports missing quotes when this flag is on,
        # but does not auto-fix. SQLFormatter reads the flag and post-processes
        # the lint output to actually add the quotes.
        "[sqlfluff:rules:references.quoting]",
        f"prefer_quoted_identifiers = {quote_identifiers}",
        "",
    ]
    return "\n".join(lines)


def write_user_sqlfluff_config(settings: Mapping[str, Any]) -> str:
    """Write the rendered config to ``USER_SQLFLUFF_PATH`` and return that path."""
    os.makedirs(USER_DATA_DIR, exist_ok=True)
    contents = render_sqlfluff_config(settings)
    try:
        with open(USER_SQLFLUFF_PATH, 'w', encoding='utf-8') as f:
            f.write(contents)
    except OSError:
        logger.exception("Failed to write SQLFluff config to %s.", USER_SQLFLUFF_PATH)
    return USER_SQLFLUFF_PATH
